# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk8

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту freelancerigor@yandex.ru если сборка упала
notifications:
  email:
    recipients:
      freelancerigor@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="1dc879be-d569-4fb9-af02-f726f69c64fe"